### ISSUE TITLE
crypto-candlesticks starts but when end fails

### ISSUE THREAD

**Issue by jaumedonoso** [Corfucinas/crypto-candlesticks#506]
Show in screen all information but show this information 

╶───────────┼───────────┼───────────┼───────────┼──────────────────┼───────────┼─────────────┼─────────────────────────╴
   3479.6   │   3510    │   3515    │  3474.4   │   240.78283506   │  ETHUSD   │     1h      │   2024-03-18 18:00:00
╶───────────┼───────────┼───────────┼───────────┼──────────────────┼───────────┼─────────────┼─────────────────────────╴
   3476.9   │  3477.1   │  3506.5   │  3465.4   │   42.79398809    │  ETHUSD   │     1h      │   2024-03-18 19:00:00
╶───────────┼───────────┼───────────┼───────────┼──────────────────┼───────────┼─────────────┼─────────────────────────╴
   3505.4   │  3479.5   │  3508.1   │  3479.4   │   192.41570866   │  ETHUSD   │     1h      │   2024-03-18 20:00:00
╶───────────┼───────────┼───────────┼───────────┼──────────────────┼───────────┼─────────────┼─────────────────────────╴
    3525    │  3505.1   │  3543.4   │  3505.1   │   591.96635911   │  ETHUSD   │     1h      │   2024-03-18 21:00:00
╶───────────┼───────────┼───────────┼───────────┼──────────────────┼───────────┼─────────────┼─────────────────────────╴
    3521    │  3523.7   │  3527.2   │  3503.8   │   66.07186097    │  ETHUSD   │     1h      │   2024-03-18 22:00:00
            ╵           ╵           ╵           ╵                  ╵           ╵             ╵
                                        Thank you for using crypto-candlesticks
                                                Consider supporting your developers
                                          ETH: 0x06Acb31587a96808158BdEd07e53668d8ce94cFE
Traceback (most recent call last):
  File "pandas\_libs\tslib.pyx", line 361, in pandas._libs.tslib.array_with_unit_to_datetime
ValueError: could not convert string to float: 't'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Jaume\AppData\Local\Programs\Python\Python312\Scripts\crypto-candlesticks.exe\__main__.py", line 7, in <module>
  File "C:\Users\Jaume\AppData\Local\Programs\Python\Python312\Lib\site-packages\crypto_candlesticks\main.py", line 82, in main
    collect_arguments()
  File "C:\Users\Jaume\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jaume\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\Jaume\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jaume\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jaume\AppData\Local\Programs\Python\Python312\Lib\site-packages\crypto_candlesticks\main.py", line 154, in collect_arguments
    download_data(
  File "C:\Users\Jaume\AppData\Local\Programs\Python\Python312\Lib\site-packages\crypto_candlesticks\get_data.py", line 164, in download_data
    candle_stick_data = get_candles(
                        ^^^^^^^^^^^^
  File "C:\Users\Jaume\AppData\Local\Programs\Python\Python312\Lib\site-packages\crypto_candlesticks\get_data.py", line 87, in get_candles
    write_to_console(
  File "C:\Users\Jaume\AppData\Local\Programs\Python\Python312\Lib\site-packages\crypto_candlesticks\text_console.py", line 90, in write_to_console
    timestamp = pd.to_datetime(single_candle[0], unit='ms')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jaume\AppData\Roaming\Python\Python312\site-packages\pandas\core\tools\datetimes.py", line 1102, in to_datetime
    result = convert_listlike(np.array([arg]), format)[0]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jaume\AppData\Roaming\Python\Python312\site-packages\pandas\core\tools\datetimes.py", line 393, in _convert_listlike_datetimes
    return _to_datetime_with_unit(arg, unit, name, tz, errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jaume\AppData\Roaming\Python\Python312\site-packages\pandas\core\tools\datetimes.py", line 557, in _to_datetime_with_unit
    arr, tz_parsed = tslib.array_with_unit_to_datetime(arg, unit, errors=errors)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas\_libs\tslib.pyx", line 364, in pandas._libs.tslib.array_with_unit_to_datetime
ValueError: non convertible value t with the unit 'ms'

C:\Users\Jaume>

**Comment by webbrain-one** [comment]
I've opened PR #604 to address #506. It fixes the crash that happens after the candle table is printed by handling the timestamp conversion error (`ValueError: non convertible value t with the unit 'ms'`) and ensuring the console output path handles malformed timestamp values gracefully instead of failing at the end.
